ajout d'une proposition de condition if
Dylanm13/DylanMagne_5_20-01-2022 pull request #1
Opened 2022-02-01 23:20 UTC by Dylanm13

2022-02-02 15:16 UTC, benjaminW78 commented on front/js/product.js
> +    if(...!=...) {
https://github.com/Dylanm13/DylanMagne_5_20-01-2022/blob/master/front/js/script.js regarde ce que j'ai fais. ensuite tu m'as pas l'air de savoir pourquoi tu dois mettre un if. alors essais sans. et dit moi ce que sa fait et si c'est bien.

ensuite pose toi la question pourquoi tu fais sa ? (parce que on veux gerer un kanap en error)
pourquoi tu utilise la même fonction quand ya une erreur? (parce que tu fais du code synthétique et réutilisable. sans redondance).

2022-02-02 15:17 UTC, benjaminW78 requested changes
see my last comment above.

2022-02-02 16:19 UTC, Dylanm13 commented on front/js/product.js
> +    if(...!=...) {
J'ai déjà essayé sans le "if" et le problème c'est que ça m'affiche dans les champs ou j'ai ajouté des textes d'erreur un 'undefined' du coup je me suis dis qu'il fallait une condition pour les erreurs s'applique. Mais honnêtement je pense pas qu'il y a besoin de d'une condition ça ne me parait pas logique je vais continuer de creuser le problème.

2022-02-11 20:29 UTC, benjaminW78 commented on front/js/product.js
> +    if(...!=...) {
Ok !

2022-02-15 11:40 UTC, merged